---
version: '3'

services:
  orion-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=orion
      - MYSQL_DATABASE=orion

  orion-server:
    restart: always
    image: cosme/orion-server
    environment:
      - DATABASE_HOST=orion-db
      - DATABASE_PORT=3306
      - DATABASE_NAME=orion
      - DATABASE_USER=root
      - DATABASE_PASSWORD=orion
    depends_on:
      - orion-db

  orion-web:
    restart: always
    image: cosme/orion-web
    environment:
      - LISTEN_PORT=80
      - SERVER_URL=orion-server
      - SERVER_PORT=80
    depends_on:
      - orion-server
    ports:
      - "80:80"
